In [7]:
# load packages 
import os 
import sys
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt 

%matplotlib inline
%config InlineBackend.figure_format = 'retina'

In [8]:
# import files 
%load_ext autoreload 
%autoreload 2

from src.data_ingestion import * 
from src.visualization import * 
from src.feature_engineering import *
from src.model_train import * 
from src.model_eval import * 

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload


In [9]:
# load data 
train_data = read_train()
test_data = read_test()
train_data.head()

Sentence Sentiment
0  According to the Finnish-Russian Chamber of Co...   neutral
1  The Swedish buyout firm has sold its remaining...   neutral
2    $SPY wouldn't be surprised to see a green close  positive
3  Shell's $70 Billion BG Deal Meets Shareholder ...  negative
4  SSH COMMUNICATIONS SECURITY CORP STOCK EXCHANG...  negative

In [14]:
from sklearn.feature_extraction.text import CountVectorizer

In [13]:
vectorizer = CountVectorizer()
X = vectorizer.fit_transform(train_data['Sentence'])
print(vectorizer.get_feature_names_out())
print(X.toarray())

['00' '000' '000063' ... 'ñrvinen' 'óeur' 'úo']
[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]
